### ISSUE TITLE
Implement Gossip Pull Responses

### ISSUE THREAD

**Issue by sonicfromnewyoke** [hexishq/velos#7]

**Comment by sonicfromnewyoke** [comment]
I believe that that project has a great future, and if you don't mind, I'd like to help you.
I'd like to start by implementing `pull responses`, not the simplest one but pretty small part of gossip

**Comment by arthur999999** [comment]
Why is it important for a light client to share information? I think the gossip protocol run by nodes prioritizes information from nodes with a minimal amount of stake.

**Comment by sonicfromnewyoke** [comment]
yeah, It looks like I slightly misunderstood the realization steps. I agree that running the service as a `spy node` (shred-version == 0) will be enough

**Comment by arthur999999** [comment]
I think this is the way, lets figure out

**Comment by arthur999999** [comment]
Hi @sonicfromnewyoke! I’m trying to understand more about CrdsFilters. You can DM me on Discord (amadeusarthur) if you’d like!
